sharded: s/func(*inst)/std::invoke(func, *inst)/
otherwise, gcc-11 fails to compile the code like:

struct echo_client {
  future<uint64_t> total_reqs() const;
};
///...
clients->map_reduce(adder<uint64_t>(), &echo_client::total_reqs);

with warning like:

/opt/rh/gcc-toolset-11/root/usr/bin/c++ -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_TYPE_ERASE_MORE -I../third-party/seastar/include -Ithird-party/seastar/gen/include -g -fcoroutines -std=gnu++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -DSEASTAR_SSTRING -Wno-error=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=c++2a -MD -MT src/CMakeFiles/echo-client.dir/echo_client.cc.o -MF src/CMakeFiles/echo-client.dir/echo_client.cc.o.d -o src/CMakeFiles/echo-client.dir/echo_client.cc.o -c ../src/echo_client.cc
In file included from ../third-party/seastar/include/seastar/core/metrics_api.hh:26,
                 from ../third-party/seastar/include/seastar/core/app-template.hh:30,
                 from ../src/echo_client.cc:4:
../third-party/seastar/include/seastar/core/sharded.hh: In instantiation of ‘typename seastar::reducer_traits<Reducer>::future_type seastar::sharded<T>::map_reduce(Reducer&&, Func&&) [with Reducer = seastar::adder<long unsigned int>; Func = seastar::future<long unsigned int> (echo_client::*)() const; Service = echo_client; typename seastar::reducer_traits<Reducer>::future_type = seastar::future<long unsigned int>]’:
../src/echo_client.cc:159:30:   required from here
../third-party/seastar/include/seastar/core/sharded.hh:329:32: error: must use ‘.*’ or ‘->*’ to call pointer-to-member function in ‘func (...)’, e.g. ‘(... ->* func) (...)’
  329 |                     return func(*inst);
      |                            ~~~~^~~~~~~
../third-party/seastar/include/seastar/core/sharded.hh:327:38: error: no matching function for call to ‘seastar::smp::submit_to(unsigned int&, seastar::sharded<echo_client>::map_reduce<seastar::adder<long unsigned int>, seastar::future<long unsigned int> (echo_client::*)() const>(seastar::adder<long unsigned int>&&, seastar::future<long unsigned int> (echo_client::*&&)() const)::<lambda(unsigned int)> mutable::<lambda()>)’
  327 |                 return smp::submit_to(c, [this, func] () mutable {
      |                        ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  328 |                     auto inst = get_local_service();
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  329 |                     return func(*inst);
      |                     ~~~~~~~~~~~~~~~~~~~
  330 |                 });
      |                 ~~

Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Message-Id: <20220506132627.918396-1-tchaikov@gmail.com>